/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FormField: typeof import('./shared/ui/form-generator/FormField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiButton: typeof import('./shared/ui/button/UiButton.vue')['default']
    UiFormGenerator: typeof import('./shared/ui/form-generator/UiFormGenerator.vue')['default']
    UiIcon: typeof import('./shared/ui/icon/UiIcon.vue')['default']
    UiInput: typeof import('./shared/ui/input/UiInput.vue')['default']
    UiPagination: typeof import('./shared/ui/pagination/UiPagination.vue')['default']
    UiSelect: typeof import('./shared/ui/select/UiSelect.vue')['default']
    UiTable: typeof import('./shared/ui/table/UiTable.vue')['default']
  }
}
