import type { Organization } from '@entities/organization/model';
import { generateId } from '@shared/lib/utils';

export const mockOrganizations: Organization[] = [
  {
    id: generateId(),
    name: 'ООО "Вектор"',
    director: 'Иванов И.И.',
    phone: '+7 900 111 22 33',
    address: { city: 'Москва', street: 'Ленина', building: '1' },
  },
  {
    id: generateId(),
    name: 'ООО "ТехноПром"',
    director: 'Сидоров С.С.',
    phone: '+7 921 456 78 90',
    address: { city: 'Санкт-Петербург', street: 'Невский проспект', building: '12' },
  },
  {
    id: generateId(),
    name: 'АО "Бета-Сервис"',
    director: 'Петров П.П.',
    phone: '+7 915 333 44 55',
    address: { city: 'Казань', street: 'Баумана', building: '7' },
  },
  {
    id: generateId(),
    name: 'ООО "Альфа Групп"',
    director: 'Кузнецов К.К.',
    phone: '+7 918 888 11 22',
    address: { city: 'Ростов-на-Дону', street: 'Большая Садовая', building: '5' },
  },
  {
    id: generateId(),
    name: 'ООО "СтройИнвест"',
    director: 'Васильев В.В.',
    phone: '+7 902 234 56 78',
    address: { city: 'Екатеринбург', street: 'Ленина', building: '42' },
  },
  {
    id: generateId(),
    name: 'ООО "ИнфоСофт"',
    director: 'Смирнов А.А.',
    phone: '+7 999 777 88 99',
    address: { city: 'Новосибирск', street: 'Красный проспект', building: '10' },
  },
  {
    id: generateId(),
    name: 'ООО "Дельта-Транс"',
    director: 'Николаев Н.Н.',
    phone: '+7 911 555 66 77',
    address: { city: 'Воронеж', street: 'Плехановская', building: '21' },
  },
  {
    id: generateId(),
    name: 'ООО "Глобал Маркет"',
    director: 'Егоров Е.Е.',
    phone: '+7 905 101 20 30',
    address: { city: 'Самара', street: 'Московское шоссе', building: '85' },
  },
  {
    id: generateId(),
    name: 'ООО "ФинГрупп"',
    director: 'Зайцев З.З.',
    phone: '+7 900 303 40 50',
    address: { city: 'Краснодар', street: 'Красная', building: '17' },
  },
  {
    id: generateId(),
    name: 'ООО "ЛогистикПро"',
    director: 'Павлов П.П.',
    phone: '+7 912 212 34 56',
    address: { city: 'Челябинск', street: 'Комсомольская', building: '8' },
  },
  {
    id: generateId(),
    name: 'ООО "СтройДом"',
    director: 'Морозов М.М.',
    phone: '+7 900 909 80 70',
    address: { city: 'Омск', street: 'Мира', building: '9' },
  },
  {
    id: generateId(),
    name: 'ООО "Ритейл-Сервис"',
    director: 'Орлов О.О.',
    phone: '+7 903 234 12 34',
    address: { city: 'Пермь', street: 'Попова', building: '14' },
  },
  {
    id: generateId(),
    name: 'ООО "Медиа Центр"',
    director: 'Киселев К.К.',
    phone: '+7 905 876 54 32',
    address: { city: 'Уфа', street: 'Октябрьская', building: '19' },
  },
  {
    id: generateId(),
    name: 'ООО "ЭкоДом"',
    director: 'Громов Г.Г.',
    phone: '+7 902 303 55 66',
    address: { city: 'Тюмень', street: 'Республики', building: '77' },
  },
  {
    id: generateId(),
    name: 'ООО "ПромТех"',
    director: 'Александров А.А.',
    phone: '+7 901 212 33 44',
    address: { city: 'Ижевск', street: 'Кирова', building: '3' },
  },
  {
    id: generateId(),
    name: 'ООО "Бизнес-Линк"',
    director: 'Соловьев С.С.',
    phone: '+7 915 700 60 50',
    address: { city: 'Барнаул', street: 'Ленина', building: '5а' },
  },
  {
    id: generateId(),
    name: 'ООО "Климат-Сервис"',
    director: 'Романов Р.Р.',
    phone: '+7 999 101 02 03',
    address: { city: 'Иркутск', street: 'Карла Маркса', building: '20' },
  },
  {
    id: generateId(),
    name: 'ООО "ИнтерПроф"',
    director: 'Титов Т.Т.',
    phone: '+7 911 404 50 60',
    address: { city: 'Хабаровск', street: 'Муравьева-Амурского', building: '2' },
  },
  {
    id: generateId(),
    name: 'ООО "Софтлайн"',
    director: 'Беляев Б.Б.',
    phone: '+7 922 111 22 44',
    address: { city: 'Томск', street: 'Советская', building: '10' },
  },
  {
    id: generateId(),
    name: 'ООО "ЭнергоПром"',
    director: 'Чернов Ч.Ч.',
    phone: '+7 905 888 77 66',
    address: { city: 'Ярославль', street: 'Свободы', building: '13' },
  },
];
